name = "RiemannHIBS"
version = "0.1.0"
defaultTargets = ["riemannhibs"]

[[lean_lib]]
name = "RiemannHIBS"

[[lean_exe]]
name = "riemannhibs"
root = "Main"

[[require]]
name = "mathlib"
git = "/Users/apple/Downloads/lean/mathlib-v4.28.0"
rev = "v4.28.0"
